import sanitizeHtml from 'sanitize-html';
import { marked } from 'marked';
// Must match NOTE_PREFIX in api/author.js: owner notes and imported articles use disjoint slug namespaces.
export const NOTE_PREFIX='note-';
// Marked explicitly requires output sanitization: https://marked.js.org/
export function cleanHtml(raw){return sanitizeHtml(raw,{exclusiveFilter:frame=>frame.tag==='img'&&(frame.attribs.width==='1'||frame.attribs.height==='1'||(frame.attribs.src||'').includes('medium.com/_/stat')),allowedTags:sanitizeHtml.defaults.allowedTags.concat(['img','figure','figcaption','h1','h2','h3','h4','h5','h6','sup','sub']),allowedAttributes:{a:['href','title'],img:['src','alt','width','height','loading','decoding','referrerpolicy'],code:['class'],th:['colspan','rowspan'],td:['colspan','rowspan']},allowedSchemes:['https','http','mailto'],allowedSchemesByTag:{img:['https']},allowProtocolRelative:false,transformTags:{img:(tag,a)=>({tagName:tag,attribs:{...a,loading:'lazy',decoding:'async',referrerpolicy:'no-referrer'}}),a:(tag,a)=>({tagName:tag,attribs:{...a,rel:'noopener noreferrer'}})}});}
// sourceUrl is rendered as a link, so only absolute HTTPS URLs (no credentials) are allowed through.
export function httpsUrl(value){if(value==null||value==='')return null;let url;try{url=new URL(value);}catch{throw Error('Invalid sourceUrl: '+value);}if(url.protocol!=='https:'||!url.hostname||url.username||url.password)throw Error('sourceUrl must be an HTTPS URL: '+value);return url.href;}
export function compileNote(note){if(note.status!=='published')return null;if(typeof note.slug!=='string'||!note.slug.startsWith(NOTE_PREFIX))throw Error(`Published note slug must start with "${NOTE_PREFIX}": ${note.slug}`);return {slug:note.slug,title:note.title,summary:note.summary||'',category:'field',date:note.publishedAt,sourceUrl:null,contentStatus:'original',html:cleanHtml(marked.parse(note.body||''))};}
export function compileMedium(article){if(typeof article.slug!=='string'||article.slug.startsWith(NOTE_PREFIX))throw Error(`Imported article slug cannot use the "${NOTE_PREFIX}" namespace: ${article.slug}`);return {slug:article.slug,title:article.title,summary:article.summary,category:article.category,date:article.date,sourceUrl:httpsUrl(article.sourceUrl),contentStatus:article.contentStatus,html:cleanHtml(article.bodyHtml)};}
