import {marked} from 'marked';import DOMPurify from 'dompurify';import TurndownService from 'turndown';import {gfm} from 'turndown-plugin-gfm';
const $=s=>document.querySelector(s),status=$('#editor-status'),form=$('#note-form'),picker=$('#note-picker'),richEditor=$('#rich-editor'),bodyField=$('#note-body'),toolbar=$('.format-toolbar'),wordCount=$('#editor-word-count');
// loadedSlug/loadedStatus describe what GitHub holds for the note in the editor; revision counts keystrokes so a save never clears edits typed while it was in flight.
let csrf='',sha=null,dirty=false,busy=false,loadedSlug='',loadedStatus=null,publicPresent=null,syncProblem=false,revision=0,request=0,storyTouched=false,storyVersion=0,storySyncTimer=0;
const NOTE_PREFIX='note-';
const fields={title:$('#note-title'),slug:$('#note-slug'),summary:$('#note-summary')};
const turndown=new TurndownService({headingStyle:'atx',bulletListMarker:'-',codeBlockStyle:'fenced',emDelimiter:'*',strongDelimiter:'**'});
turndown.use(gfm);
const controls=()=>[picker,$('#new-note'),$('#sign-out'),...form.querySelectorAll('button')];
const state=document.createElement('p');state.id='note-state';state.className='fine-print';state.setAttribute('aria-live','polite');$('#editor .button-row').after(state);
function message(text,error=false){status.textContent=text;status.classList.toggle('error',error);}
function renderState(){state.dataset.status=syncProblem?'out-of-sync':loadedStatus||'new';const savedState=syncProblem?`private source is ${loadedStatus||'unknown'}, but its public state needs reconciliation`:loadedStatus==='published'?'PUBLISHED on the public journal':'a private draft';state.textContent=(loadedSlug?`Editing ${loadedSlug}: ${savedState}.`:'New note: not saved to GitHub yet.')+(dirty?' Unsaved changes.':'');}
// Loading replaces every field, so fields lock too; saving only locks the slug so typing can continue.
function setBusy(on,lockFields=false){busy=on;for(const c of controls())c.disabled=on;fields.slug.readOnly=on||Boolean(loadedSlug);for(const k of ['title','summary'])fields[k].readOnly=on&&lockFields;richEditor.contentEditable=on&&lockFields?'false':'true';richEditor.setAttribute('aria-busy',String(on&&lockFields));}
async function api(action,options={}){const r=await fetch('/api/author?action='+action,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers}});let data;try{data=await r.json();}catch{throw Error('Authoring API is unavailable. Deploy on Vercel with the documented server configuration.');}if(!r.ok){const error=Error(data.error||'Request failed');error.payload=data;throw error;}return data;}
function safeHtml(html){return DOMPurify.sanitize(html,{FORBID_TAGS:['style','script','iframe','form','input','button','object','embed'],FORBID_ATTR:['style','onerror','onload']});}
function normalizeUrls(container){for(const element of container.querySelectorAll('a[href],img[src]')){const attribute=element.matches('a')?'href':'src',value=element.getAttribute(attribute)||'';if(value.startsWith('/')||element.matches('a')&&value.startsWith('#'))continue;try{const protocol=new URL(value,location.origin).protocol,allowed=protocol==='https:'||element.matches('a')&&protocol==='mailto:';if(!allowed)element.removeAttribute(attribute);}catch{element.removeAttribute(attribute);}}}
function markdownFromEditor(){const staging=document.createElement('div');staging.innerHTML=safeHtml(richEditor.innerHTML);normalizeUrls(staging);return turndown.turndown(staging.innerHTML).trim();}
function updateMetrics(){const text=richEditor.innerText.trim(),words=text?text.split(/\s+/u).length:0,minutes=words?Math.max(1,Math.ceil(words/220)):0;wordCount.textContent=`${words} ${words===1?'word':'words'} · ${minutes} min read`;}
function preview(){$('#note-preview').innerHTML=safeHtml(marked.parse(bodyField.value));}
function syncFromEditor(markDirty=true){clearTimeout(storySyncTimer);bodyField.value=markdownFromEditor();updateMetrics();preview();if(markDirty){storyTouched=true;storyVersion++;revision++;dirty=true;renderState();}}
function scheduleStorySync(){storyTouched=true;storyVersion++;revision++;dirty=true;updateMetrics();renderState();clearTimeout(storySyncTimer);storySyncTimer=setTimeout(()=>syncFromEditor(false),140);}
function setStory(markdown=''){clearTimeout(storySyncTimer);bodyField.value=markdown;richEditor.innerHTML=safeHtml(marked.parse(markdown));normalizeUrls(richEditor);storyTouched=false;updateMetrics();preview();}
function noteFromForm(){if(storyTouched)syncFromEditor(false);return {title:fields.title.value,slug:fields.slug.value,summary:fields.summary.value,body:bodyField.value};}
function ensureOption(slug){if(slug&&![...picker.options].some(o=>o.value===slug))picker.add(new Option(slug,slug));picker.value=loadedSlug;}
function clear(){request++;sha=null;loadedSlug='';loadedStatus=null;publicPresent=null;syncProblem=false;for(const field of Object.values(fields))field.value='';setStory('');delete fields.slug.dataset.edited;fields.slug.readOnly=false;picker.value='';dirty=false;revision++;renderState();message('New note. Nothing saved yet.');}
async function list(){const data=await api('notes');picker.replaceChildren(new Option('New note',''));for(const note of data.notes)picker.add(new Option(note.slug,note.slug));ensureOption(loadedSlug);}
async function load(slug){const ticket=++request;setBusy(true,true);message('Loading '+slug+'…');try{const data=await api('note&slug='+encodeURIComponent(slug));if(ticket!==request)return;for(const [k,f] of Object.entries(fields))f.value=data.note[k]||'';setStory(data.note.body||'');sha=data.sha;loadedSlug=slug;loadedStatus=data.note.status;publicPresent=data.publicPresent;syncProblem=data.publicSynced===false;dirty=false;revision++;message(syncProblem?'Loaded the private source, but its public state needs reconciliation. Retry publish or save as draft.':'Loaded '+data.note.status+' from GitHub.',syncProblem);}catch(e){if(ticket!==request)return;picker.value=loadedSlug;message(e.message,true);}finally{if(ticket===request){setBusy(false);renderState();}}}
for(const field of Object.values(fields))field.addEventListener('input',()=>{revision++;dirty=true;renderState();});
richEditor.addEventListener('input',scheduleStorySync);
fields.title.addEventListener('input',()=>{if(!loadedSlug&&!busy&&!fields.slug.dataset.edited){const words=fields.title.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80-NOTE_PREFIX.length).replace(/-$/,'');fields.slug.value=words?NOTE_PREFIX+words:'';}});fields.slug.addEventListener('input',()=>fields.slug.dataset.edited='true');
function selectionRange(){const selection=getSelection();return selection&&selection.rangeCount?selection.getRangeAt(0).cloneRange():null;}
function restoreSelection(range){if(!range)return;const selection=getSelection();selection.removeAllRanges();selection.addRange(range);}
function insertHtml(html){richEditor.focus();document.execCommand('insertHTML',false,html);syncFromEditor(true);}
function escapeHtml(text){return text.replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));}
function selectedCode(range){if(!range)return 'code';const blocks=new Set(['ADDRESS','ARTICLE','ASIDE','BLOCKQUOTE','DIV','DL','DT','DD','FIGCAPTION','FIGURE','FOOTER','H1','H2','H3','H4','H5','H6','HEADER','LI','MAIN','NAV','OL','P','PRE','SECTION','UL']);const fragment=range.cloneContents();function plain(node){if(node.nodeType===Node.TEXT_NODE)return node.textContent;if(node.nodeName==='BR')return '\n';let text='';for(const child of node.childNodes)text+=plain(child);if(blocks.has(node.nodeName)&&text&&!text.endsWith('\n'))text+='\n';return text;}return plain(fragment).replace(/\n{3,}/g,'\n\n').trim()||'code';}
function applyCommand(command,value=false){const before=richEditor.innerHTML;document.execCommand(command,false,value);if(richEditor.innerHTML!==before)syncFromEditor(true);}
toolbar.addEventListener('mousedown',event=>event.preventDefault());
toolbar.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;richEditor.focus();if(button.dataset.command){applyCommand(button.dataset.command);return;}if(button.dataset.block){applyCommand('formatBlock',button.dataset.block);return;}if(button.dataset.action==='divider'){insertHtml('<hr><p><br></p>');return;}if(button.dataset.action==='code'){const range=selectionRange(),code=selectedCode(range);restoreSelection(range);insertHtml(`<pre><code>${escapeHtml(code)}</code></pre><p><br></p>`);return;}if(button.dataset.action==='link'){const range=selectionRange(),value=prompt('Paste an HTTPS link or email address');if(value===null)return;try{const url=new URL(value.includes('@')&&!value.includes(':')?'mailto:'+value:value),allowed=url.protocol==='https:'||url.protocol==='mailto:';if(!allowed)throw Error();restoreSelection(range);applyCommand('createLink',url.href);}catch{message('Links must use HTTPS or a valid email address.',true);}return;}if(button.dataset.action==='image'){const range=selectionRange(),value=prompt('Paste an HTTPS image URL');if(value===null)return;try{const url=new URL(value);if(url.protocol!=='https:')throw Error();const alt=prompt('Describe the image for readers')||'';restoreSelection(range);insertHtml(`<figure><img src="${url.href}" alt="${escapeHtml(alt)}"></figure><p><br></p>`);}catch{message('Images must use a valid HTTPS URL.',true);}}});
richEditor.addEventListener('paste',event=>{const html=event.clipboardData?.getData('text/html');if(!html)return;event.preventDefault();const staging=document.createElement('div');staging.innerHTML=safeHtml(html);normalizeUrls(staging);insertHtml(staging.innerHTML);});
let internalDrag=false;
richEditor.addEventListener('dragstart',()=>internalDrag=true);
richEditor.addEventListener('dragend',()=>internalDrag=false);
richEditor.addEventListener('drop',event=>{if(internalDrag){internalDrag=false;return;}event.preventDefault();let range=document.caretRangeFromPoint?.(event.clientX,event.clientY);if(!range&&document.caretPositionFromPoint){const caret=document.caretPositionFromPoint(event.clientX,event.clientY);if(caret){range=document.createRange();range.setStart(caret.offsetNode,caret.offset);range.collapse(true);}}restoreSelection(range);const html=event.dataTransfer?.getData('text/html'),text=event.dataTransfer?.getData('text/plain');if(html){const staging=document.createElement('div');staging.innerHTML=safeHtml(html);normalizeUrls(staging);insertHtml(staging.innerHTML);}else if(text)insertHtml(escapeHtml(text).replace(/\r?\n/g,'<br>'));});
$('#new-note').addEventListener('click',()=>{if(busy)return;if(!dirty||confirm('Discard unsaved changes?'))clear();});
picker.addEventListener('change',async()=>{const slug=picker.value;if(busy||(dirty&&!confirm('Discard unsaved changes and load this note?'))){picker.value=loadedSlug;return;}if(!slug){clear();return;}await load(slug);});
form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const publish=e.submitter?.dataset.status==='published';const note=noteFromForm();
 if(!note.body){message('Write something before saving the note.',true);richEditor.focus();return;}
 if(note.body.length>80000){message('The story is too long. Keep it under 80,000 Markdown characters.',true);return;}
 if(!note.slug.startsWith(NOTE_PREFIX)){message(`The URL identifier must start with "${NOTE_PREFIX}" so it cannot collide with imported articles.`,true);return;}
 if(publish&&!confirm('Publish this note to the public journal on the next successful deployment?'))return;
 const unpublish=!publish&&(loadedStatus==='published'||publicPresent===true||syncProblem);
 if(unpublish&&!confirm(syncProblem?'This note has an unresolved public sync. Save it as a draft and remove any public copy?':'This note is currently published. Saving it as a draft removes it from the public journal on the next deployment. Unpublish it?'))return;
 const rev=revision,storyRev=storyVersion;let data;const payload={...note,status:publish?'published':'draft',sha,...(unpublish?{unpublish:true}:{})};setBusy(true);message('Saving to GitHub…');
 try{data=await api('save',{method:'POST',body:JSON.stringify(payload)});}catch(firstError){let error=firstError;if(firstError.payload?.unpublishRequired&&!payload.unpublish&&confirm('A public copy of this note already exists. Save this version as a draft and remove the public copy?')){payload.unpublish=true;message('Reconciling the public copy…');try{data=await api('save',{method:'POST',body:JSON.stringify(payload)});}catch(retryError){error=retryError;}}if(!data){if(error.payload?.saved&&error.payload.note){sha=error.payload.sha;loadedSlug=error.payload.note.slug;loadedStatus=error.payload.note.status;publicPresent=error.payload.publicState==='present'?true:error.payload.publicState==='absent'?false:null;syncProblem=error.payload.publicSynced===false||publicPresent===null;dirty=revision!==rev;storyTouched=storyVersion!==storyRev;ensureOption(loadedSlug);}setBusy(false);renderState();message(error.message,true);return;}}
 sha=data.sha;loadedSlug=data.note.slug;loadedStatus=data.note.status;publicPresent=data.publicPresent;syncProblem=data.publicSynced===false;dirty=revision!==rev;storyTouched=storyVersion!==storyRev;
 const saved=(publish?'Published commit verified in GitHub. The public page updates after Vercel finishes its build.':'Draft saved and verified in the private repository. It is not included in the public build.')+(dirty?' Edits typed while saving are not saved yet.':'');
 try{await list();message(saved);}catch(error){ensureOption(loadedSlug);message(saved+' However, the saved-notes list could not refresh ('+error.message+'). Reload to see the full list.',true);}
 finally{setBusy(false);renderState();}
});
$('#export-note').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(noteFromForm(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(fields.slug.value||'note')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('#sign-out').addEventListener('click',async()=>{if(busy)return;if(dirty&&!confirm('Sign out and discard unsaved edits?'))return;try{await api('logout',{method:'POST'});dirty=false;location.reload();}catch(e){message(e.message,true);}});
addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
renderState();updateMetrics();
try{const session=await api('session');csrf=session.csrf;$('#auth-panel').hidden=true;$('#editor').hidden=false;await list();message('Signed in as '+session.login+'.');}catch(e){$('#auth-message').textContent=e.message;$('#sign-in').hidden=/not configured|unavailable/.test(e.message);}
